### ISSUE TITLE
No es ningún issue

### ISSUE THREAD

**Issue by pacocp** [mgmacias95/Analisis-Resultados-R-Python#1]
No es ningún issue, simplemente para decirte que ¡buen trabajo y que muy interesante! Me plantearé hacer las cosas así a partir de ahora, aun que mi querida línea de comandos con gnuplot es muy querida.
Puedes cerrarme en cuánto lo leas jajaja

¡Un saludo!

**Comment by mgmacias95** [comment]
Hola @pacocp :P me alegra de que te haya gustado/inspirado el repo jaja. 

Yo la verdad es que usé una vez gnuplot para una práctica pero no lo volví a usar XD (no porque no me gustara sino porque no lo volví a necesitar), así que no tenía ningún "favorito" para gráficas. ggplot2 me gustó bastante y era muy sencillo de usar, además de que creo que da unas gráficas más bonitas que gnuplot pero cada uno es libre de usar lo que quiera (incluso el Excel.. XD). 

Un saludo ;)
